spring:
  application:
    name: service
server:
  port: 8762
eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info